= Istio Multi Revision Demo

== Pre-requisites

* https://asdf-vm.com[asdf-vm]
* Kubernetes Cluster
* https://kubernetes.io/docs/tasks/tools/[kubectl]
* https://httpie.io[httpie]
* https://docs.solo.io/gloo-edge/latest/getting_started/[glooctl]
** https://kind.sigs.k8s.io[KinD]
** https://civo.com[Civo]
* https://docs.solo.io/gloo-edge/latest/getting_started/[Gloo Edge]

== Download Sources

[source,bash]
----
git clone https://github.com/kameshsampath/istio-multi-rev-demo istio-multi-rev-demo && cd $_
----

We will refer to the cloned folder as `$PROJECT_HOME`:

[source,bash]
----
export PROJECT_HOME="$(pwd)"
----

== Install asdf-istio plugin

[source,bash]
----
asdf plugin-add istio https://github.com/kameshsampath/asdf-istio
----

== Setup Kubernetes Cluster

For the examples we will be using the KinD as our Kubernetes cluster, run the following command to start single node Kubernetes cluster:

[source,bash]
----
$PROJECT_HOME/start-kind.sh
----

NOTE: You would have already done this step when deploying `v1.8.6`

== Deploy Istio Control Plane

Download and install Istio v1.10.2:

[source,bash]
----
cd $PROJECT_HOME
asdf install
----

Once Istio is downloaded, let us setup an Istio control plane with a pinned revision `1.10.2`,

[source,bash]
----
$PROJECT_HOME/istio/installControlPlane.sh
----

The installation should show an output like:

[source,text]
----
Appling Istio Revision: 1-10-2
Skipping creation of namespace istio-system - already exists
Skipping creation of service istiod - already exists
WARNING: Istio is being upgraded from 1.8.6 -> 1.10.2.
WARNING: Before upgrading, you may wish to use 'istioctl analyze' to check forIST0002 and IST0135 deprecation warnings.
✔ Istio core installed
✔ Istiod installed
✔ Installation complete                                                                                            Thank you for installing Istio 1.10.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/KjkrDnMPByq7akrYA
----

Let us now verify the installation by selecting the pods in `istio-system` namespace and list the label `istio.io/rev':

[source]
----
kubectl get pods -n istio-system -L'istio.io/rev'
----

[source,bash]
----
NAME                             READY   STATUS    RESTARTS   AGE   REV
istiod-1-10-2-79d64cf497-ltqx9   1/1     Running   0          43s   1-10-2 #<1>
istiod-1-8-6-869d57f467-vnz29    1/1     Running   0          77m   1-8-6 #<2>
----
<1> Istio Control Plane configured with revision `1-10-2` corresponding to `v1.10.2`
<2> The revision `1-8-6` is that of `v1.8.6` version that was installed earlier


== Build Application

We don't need to build the application as we will be reusing the same image that we built as part of *Istio v1.8.6* deployment.

== Deploy application

The application is a simple greeter application with a REST API at `/api/hello` that sends a JSON response with a greeting, Istio revision used and service revision.

[source,bash]
----
kubectl apply -k $PROJECT_HOME/k8s/app
----

Wait for pods to be in running state:

[source,bash]
----
watch kubectl get pods -n demo-1-10-2
----

A successful deployment should show the following pods:

[source,bash]
----
NAME                           READY   STATUS    RESTARTS   AGE
curler                         2/2     Running   0          71s
hello-world-7948d8587c-c68nn   2/2     Running   0          71s
----

== Accessing the application

We will use https://docs.solo.io/gloo-edge/latest/introduction/[Gloo Edge] as API gateway to access the application:

=== Route

Gloo should be able to gather the available upstreams, lets check if our demo service upstream is available:

[source,bash]
----
export DEMO_UPSTREAMS=($(kubectl get upstreams.gloo.solo.io -ojsonpath='{.items[?(@.spec.kube.serviceName=="hello-world")].metadata.name }' -n gloo-system))
for u in "${DEMO_UPSTREAMS[@]}"
do
  glooctl get upstreams "$u"
done
----

The command should shown an output like:

Let's check its status:

[source,text]
----
+------------------------------+------------+----------+----------------------------+
|           UPSTREAM           |    TYPE    |  STATUS  |          DETAILS           |
+------------------------------+------------+----------+----------------------------+
| demo-1-10-2-hello-world-8080 | Kubernetes | Accepted | svc name:      hello-world |
|                              |            |          | svc namespace: demo-1-10-2 |
|                              |            |          | port:          8080        |
|                              |            |          |                            |
+------------------------------+------------+----------+----------------------------+
+-----------------------------+------------+----------+----------------------------+
|          UPSTREAM           |    TYPE    |  STATUS  |          DETAILS           |
+-----------------------------+------------+----------+----------------------------+
| demo-1-8-6-hello-world-8080 | Kubernetes | Accepted | svc name:      hello-world |
|                             |            |          | svc namespace: demo-1-8-6  |
|                             |            |          | port:          8080        |
|                             |            |          |                            |
+-----------------------------+------------+----------+----------------------------+
----

Let us now update the route to distribute the traffic between the `1.8.6`(70%) and `1.10.2`(30%) revision:

[source,bash]
----
kubectl apply -f $PROJECT_HOME/gloo/gateway.yaml
# virtualservice.gateway.solo.io/istio-multi-rev-demo created
----

Run the script `$PROJECT_HOME/run.sh` to send few requests to our API and you should see the following responses with traffic getting to the demo service with revision `1-8-6`:

[source,text]
----
{
    "istioRevision": "1-8-6",
    "message": "HelloWorld  hello-world-dbb687654-jvnxw from greeting service 'v1.0': 2",
    "serviceVersion": "v1.0"
}


{
    "istioRevision": "1-8-6",
    "message": "HelloWorld  hello-world-dbb687654-jvnxw from greeting service 'v1.0': 3",
    "serviceVersion": "v1.0"
}


{
    "istioRevision": "1-8-6",
    "message": "HelloWorld  hello-world-dbb687654-jvnxw from greeting service 'v1.0': 4",
    "serviceVersion": "v1.0"
}
{
  "istioRevision": "1-10-2",
  "message": "HelloWorld  hello-world-7948d8587c-c68nn from greeting service 'v2.0': 1",
  "serviceVersion": "v2.0"
}
{
  "istioRevision": "1-10-2",
  "message": "HelloWorld  hello-world-7948d8587c-c68nn from greeting service 'v2.0': 2",
  "serviceVersion": "v2.0"
}

----

Let us also make sure the right version of `istio-proxy` is injected:

[source,bash]
----
kubectl get  pod -lapp=hello-world -n demo-1-10-2 -ojsonpath='{.items[*].spec.containers[?(@.name == "istio-proxy")].image}'
----

The command should return an output like `docker.io/istio/proxyv2:1.10.2`
