apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpie
    sidecar.istio.io/inject: "false"
  name: httpie
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
      image: alpine/httpie
      name: httpie
