apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: curl
  name: curler
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - tail -f /dev/null
    image: curlimages/curl
    name: curler
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
